name: repo_viewer
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  oauth2: ^2.0.0
  flutter_secure_storage: ^6.0.0 
  dartz: ^0.10.1
  dio: ^4.0.6
  flutter_hooks: ^0.18.5+1
  hooks_riverpod: ^2.0.2
  freezed_annotation: ^1.1.0
  webview_flutter: ^3.0.4
  flash: ^2.0.5
  auto_route: ^3.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.1.7
  freezed: ^1.1.1
  lint: ^1.10.0
  auto_route_generator: ^3.2.1

flutter:
  uses-material-design: true
